### ISSUE TITLE
Firefox pop up error

### ISSUE THREAD

**Issue by J-Mantovani** [techslogi/SnowCaseReminder#1]
The popup box when, clicked on update, vanishes automatically without any user action, only on Mozilla Firefox.

Mozilla Firefox 62.0 (64-bit)
Windows 10 (64-bit)

**Comment by techslogi** [comment]
Please check after commit 45467a0d4eb6f1af894f2f431b38c76605f34de3. Should be working fine now.

**Comment by J-Mantovani** [comment]
Error fixed! Thanks!

**Comment by J-Mantovani** [comment]
The popup works like a charm now! But when I click on the "ok" button it simply doesn't add the case to the Case Reminder list.

Mozilla Firefox 62.0 (64-bit)
Windows 10 (64-bit)
